# Generated by Django 3.0.9 on 2020-08-05 19:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('authors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('published_date', models.CharField(blank=True, max_length=10)),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, null=True, size=None)),
                ('average_rating', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('ratings_count', models.PositiveIntegerField(blank=True, default=0)),
                ('thumbnail', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
